dist: focal
language: python

env:
  global:
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
    - COVERALLS_SERVICE_NAME=coveralls-python

python:
  - "3.11"
# Install dependencies
install:
  - pip install -r requirements.txt
# Change directory
before_script:
  - python manage.py migrate
# Run format and lint checks
script:
  - black .
  - flake8 .
  - coverage run manage.py test
  - coverage report
  - coveralls
#before_deploy:
#  - python manage.py migrate

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: SE-Assignmnet-2
  env: se-hw-2-env
  bucket_name: 'elasticbeanstalk-us-east-1-590183680251'
  on:
    all_branches: true
#    repo: allen505/swe1-app
#    branches:
#      only:
#        - master